spring:
#  You can also use Mailtrap which is an Email Delivery Platform. You have to create an account https://mailtrap.io/
  mail:
    host: smtp.mailtrap.io
    port: 25
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: <put-your-smtp-username>
    password: <put-your-smtp-password>