spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  #      naming:
#        implicit-strategy:
#        physical-strategy:

#https://hackernoon.com/using-postgres-effectively-in-spring-boot-applications